"""initial schema

Revision ID: 7d5639666ab9
Revises: 
Create Date: 2026-07-30 17:30:50.956116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5639666ab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cv_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_time', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=True)
    op.create_index(op.f('ix_experiments_target_column'), 'experiments', ['target_column'], unique=False)
    op.create_table('category_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('top_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('average_importance', sa.Float(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_patterns_experiment_id'), 'category_patterns', ['experiment_id'], unique=False)
    op.create_table('feature_importances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_importances_experiment_id'), 'feature_importances', ['experiment_id'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_class', sa.String(length=100), nullable=False),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_experiment_id'), 'prediction_logs', ['experiment_id'], unique=False)
    op.create_table('safety_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('stakeholder', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_recommendations_experiment_id'), 'safety_recommendations', ['experiment_id'], unique=False)
    op.create_table('training_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('model_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(op.f('ix_safety_recommendations_experiment_id'), table_name='safety_recommendations')
    op.drop_table('safety_recommendations')
    op.drop_index(op.f('ix_prediction_logs_experiment_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_feature_importances_experiment_id'), table_name='feature_importances')
    op.drop_table('feature_importances')
    op.drop_index(op.f('ix_category_patterns_experiment_id'), table_name='category_patterns')
    op.drop_table('category_patterns')
    op.drop_index(op.f('ix_experiments_target_column'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
