"""add recommendation workflow and classification fields

Revision ID: 99b2242564e3
Revises: 6e614830a4f0
Create Date: 2026-08-04 20:10:31.972076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b2242564e3'
down_revision: Union[str, Sequence[str], None] = '6e614830a4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_recommendations', sa.Column('icao_reference', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('safety_recommendations', sa.Column('hfacs_classification', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('safety_recommendations', sa.Column('swiss_cheese_layer', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('safety_recommendations', sa.Column('status', sa.String(length=20), nullable=False, server_default='Open'))
    op.add_column('safety_recommendations', sa.Column('assigned_officer', sa.String(length=150), nullable=True))
    op.add_column('safety_recommendations', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_safety_recommendations_status'), 'safety_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_recommendations_status'), table_name='safety_recommendations')
    op.drop_column('safety_recommendations', 'due_date')
    op.drop_column('safety_recommendations', 'assigned_officer')
    op.drop_column('safety_recommendations', 'status')
    op.drop_column('safety_recommendations', 'swiss_cheese_layer')
    op.drop_column('safety_recommendations', 'hfacs_classification')
    op.drop_column('safety_recommendations', 'icao_reference')
    # ### end Alembic commands ###
