"""add categorical_encodings

Revision ID: d42124a345f5
Revises: 7d5639666ab9
Create Date: 2026-07-30 18:49:41.353337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42124a345f5'
down_revision: Union[str, Sequence[str], None] = '7d5639666ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('categorical_encodings', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'categorical_encodings')
    # ### end Alembic commands ###
