"""
Safety Recommendation Centre endpoints -- cross-experiment recommendation
listing/filtering/search plus workflow updates (status, assignment, due date).
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from src.database.base import get_db
from src.database.repositories import ExperimentRepository, RecommendationRepository

from .. import schemas
from ..services import recommendation_service
from ..services.prediction_service import PredictionError

router = APIRouter(prefix="/recommendations", tags=["recommendations"])


@router.get("", response_model=list[schemas.RecommendationOut])
def list_recommendations(
    category: str | None = None,
    priority: str | None = None,
    status: str | None = None,
    search: str | None = None,
    limit: int = 200,
    db: Session = Depends(get_db),
) -> list:
    try:
        return RecommendationRepository.list(
            db,
            category=category,
            priority=priority,
            status=status,
            search=search,
            limit=limit,
        )
    except Exception:
        return []


@router.post("", response_model=schemas.RecommendationOut, status_code=201)
def create_recommendation(
    payload: schemas.RecommendationCreate,
    db: Session = Depends(get_db),
):
    """
    Manually author a recommendation -- not generated by
    `RecommendationEngine`, so it's stored with source="manual".
    """
    try:
        if payload.experiment_id is not None:
            experiment = ExperimentRepository.get(db, payload.experiment_id)
            if experiment is None:
                raise HTTPException(status_code=404, detail="Experiment not found")

        return RecommendationRepository.create(
            db,
            category=payload.category,
            priority=payload.priority,
            recommendation=payload.recommendation,
            stakeholder=payload.stakeholder,
            confidence=payload.confidence,
            evidence=payload.evidence,
            icao_reference=payload.icao_reference,
            hfacs_classification=payload.hfacs_classification,
            swiss_cheese_layer=payload.swiss_cheese_layer,
            experiment_id=payload.experiment_id,
            source="manual",
        )
    except HTTPException:
        raise
    except Exception:
        raise HTTPException(status_code=500, detail="Database error")


@router.post("/simulate", response_model=schemas.RecommendationSimulateResponse)
def simulate_recommendations(
    payload: schemas.RecommendationSimulateRequest,
    db: Session = Depends(get_db),
):
    """
    Run a hypothetical scenario through the trained model and return the
    recommendations its predicted category + SHAP-dominant features would
    match, without persisting a prediction log or a recommendation row.
    """
    try:
        experiment = ExperimentRepository.get(db, payload.experiment_id)

        if experiment is None:
            raise HTTPException(status_code=404, detail="Experiment not found")

        try:
            predicted_class, probabilities, dominant_features, recommendations = (
                recommendation_service.simulate(experiment, payload.features)
            )
        except PredictionError as exc:
            raise HTTPException(status_code=422, detail=str(exc)) from exc

        return schemas.RecommendationSimulateResponse(
            predicted_class=predicted_class,
            probabilities=probabilities,
            dominant_features=dominant_features,
            recommendations=[
                schemas.SimulatedRecommendation(
                    category=rec.accident_category,
                    priority=rec.priority,
                    recommendation=rec.recommendation,
                    stakeholder=rec.stakeholder,
                    confidence=rec.confidence,
                    evidence=rec.evidence,
                    icao_reference=rec.icao_reference,
                    hfacs_classification=rec.hfacs_classification,
                    swiss_cheese_layer=rec.swiss_cheese_layer,
                )
                for rec in recommendations
            ],
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Simulation error: {exc}") from exc


@router.patch("/{recommendation_id}", response_model=schemas.RecommendationOut)
def update_recommendation(
    recommendation_id: int,
    payload: schemas.RecommendationUpdate,
    db: Session = Depends(get_db),
):
    try:
        record = RecommendationRepository.get(db, recommendation_id)

        if record is None:
            raise HTTPException(status_code=404, detail="Recommendation not found")

        return RecommendationRepository.update_workflow(
            db,
            record,
            status=payload.status,
            assigned_officer=payload.assigned_officer,
            due_date=payload.due_date,
        )
    except HTTPException:
        raise
    except Exception:
        raise HTTPException(status_code=500, detail="Database error")


@router.delete("/{recommendation_id}", status_code=204)
def delete_recommendation(
    recommendation_id: int,
    db: Session = Depends(get_db),
):
    """
    Only manually-authored recommendations can be deleted -- rule-engine
    recommendations are a record of what a training run found and stay
    in place for audit purposes (dismiss via status instead).
    """
    try:
        record = RecommendationRepository.get(db, recommendation_id)

        if record is None:
            raise HTTPException(status_code=404, detail="Recommendation not found")

        if record.source != "manual":
            raise HTTPException(
                status_code=403,
                detail="Only manually-authored recommendations can be deleted",
            )

        RecommendationRepository.delete(db, record)
    except HTTPException:
        raise
    except Exception:
        raise HTTPException(status_code=500, detail="Database error")
