"""
SQLAlchemy ORM models for AviSafe.

One row in `experiments` per completed training run (mirrors the
Experiment dataclass in src/models/experiment.py, but is the
database-backed source of truth once the API is involved). Everything
the explainability layer produces for that run -- global feature
importance, per-category patterns, and safety recommendations -- is
stored as child rows so a full experiment can be reconstructed with a
single query.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime

from sqlalchemy import Date, DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


class Experiment(Base):
    __tablename__ = "experiments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    experiment_id: Mapped[str] = mapped_column(
        String(36), unique=True, default=lambda: str(uuid.uuid4()), index=True
    )

    model_name: Mapped[str] = mapped_column(String(100))

    dataset_name: Mapped[str] = mapped_column(String(255))

    target_column: Mapped[str] = mapped_column(String(100), index=True)

    model_path: Mapped[str] = mapped_column(String(500))

    random_state: Mapped[int] = mapped_column(Integer, default=42)

    parameters: Mapped[dict] = mapped_column(JSONB, default=dict)

    cv_metrics: Mapped[dict] = mapped_column(JSONB, default=dict)

    test_metrics: Mapped[dict] = mapped_column(JSONB, default=dict)

    feature_names: Mapped[list] = mapped_column(JSONB, default=list)

    categorical_encodings: Mapped[dict] = mapped_column(JSONB, default=dict)

    target_label_map: Mapped[dict] = mapped_column(JSONB, default=dict)

    training_time: Mapped[float] = mapped_column(Float, default=0.0)

    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    feature_importances: Mapped[list["FeatureImportanceRecord"]] = relationship(
        back_populates="experiment", cascade="all, delete-orphan"
    )

    recommendations: Mapped[list["SafetyRecommendationRecord"]] = relationship(
        back_populates="experiment", cascade="all, delete-orphan"
    )

    patterns: Mapped[list["CategoryPatternRecord"]] = relationship(
        back_populates="experiment", cascade="all, delete-orphan"
    )

    predictions: Mapped[list["PredictionLog"]] = relationship(
        back_populates="experiment"
    )


class FeatureImportanceRecord(Base):
    __tablename__ = "feature_importances"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), index=True
    )

    feature: Mapped[str] = mapped_column(String(255))

    importance: Mapped[float] = mapped_column(Float)

    rank: Mapped[int] = mapped_column(Integer)

    experiment: Mapped["Experiment"] = relationship(
        back_populates="feature_importances"
    )


class SafetyRecommendationRecord(Base):
    __tablename__ = "safety_recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Nullable: a rule-engine recommendation is always tied to the
    # experiment whose patterns produced it, but a manually-authored one
    # (see `source` below) is a standalone entry not derived from any
    # specific training run.
    experiment_id: Mapped[int | None] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), index=True, nullable=True
    )

    category: Mapped[str] = mapped_column(String(100))

    priority: Mapped[str] = mapped_column(String(20))

    recommendation: Mapped[str] = mapped_column(Text)

    stakeholder: Mapped[str] = mapped_column(String(100))

    confidence: Mapped[float] = mapped_column(Float)

    evidence: Mapped[list] = mapped_column(JSONB, default=list)

    icao_reference: Mapped[str] = mapped_column(String(255), default="")

    hfacs_classification: Mapped[str] = mapped_column(String(255), default="")

    swiss_cheese_layer: Mapped[str] = mapped_column(String(100), default="")

    status: Mapped[str] = mapped_column(String(20), default="Open", index=True)

    assigned_officer: Mapped[str | None] = mapped_column(String(150), nullable=True)

    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # "rule_engine" (default, generated by RecommendationEngine from
    # discovered patterns) or "manual" (authored directly by a user via
    # the Recommendation Centre, optionally seeded from a simulated
    # scenario's matched rule).
    source: Mapped[str] = mapped_column(String(20), default="rule_engine")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    experiment: Mapped["Experiment | None"] = relationship(back_populates="recommendations")


class CategoryPatternRecord(Base):
    __tablename__ = "category_patterns"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id", ondelete="CASCADE"), index=True
    )

    category: Mapped[str] = mapped_column(String(100))

    top_features: Mapped[list] = mapped_column(JSONB, default=list)

    average_importance: Mapped[float] = mapped_column(Float)

    occurrences: Mapped[int] = mapped_column(Integer)

    confidence: Mapped[float] = mapped_column(Float)

    # SHAP+LIME cross-validation (src/explainability/causal_pattern_map.py)
    # -- empty/zero for experiments trained before this field existed,
    # never backfilled or fabricated for them.
    lime_top_features: Mapped[list] = mapped_column(JSONB, default=list)

    consensus_features: Mapped[list] = mapped_column(JSONB, default=list)

    agreement_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)

    experiment: Mapped["Experiment"] = relationship(back_populates="patterns")


class TrainingJob(Base):
    __tablename__ = "training_jobs"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )

    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)

    target_column: Mapped[str] = mapped_column(String(100))

    model_candidates: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    experiment_id: Mapped[int | None] = mapped_column(
        ForeignKey("experiments.id"), nullable=True
    )

    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    experiment: Mapped["Experiment | None"] = relationship()


class RiskRegisterEntry(Base):
    __tablename__ = "risk_register_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    title: Mapped[str] = mapped_column(String(200))

    category: Mapped[str] = mapped_column(String(100), default="", index=True)

    description: Mapped[str] = mapped_column(Text, default="")

    # 1-5 ICAO-style risk matrix scales; risk_score and risk_level are
    # derived from these two at write time (see RiskRegisterRepository),
    # not independently editable, so they can never drift out of sync.
    likelihood: Mapped[int] = mapped_column(Integer)

    severity: Mapped[int] = mapped_column(Integer)

    risk_score: Mapped[int] = mapped_column(Integer, index=True)

    risk_level: Mapped[str] = mapped_column(String(20), index=True)

    status: Mapped[str] = mapped_column(String(30), default="Identified", index=True)

    owner: Mapped[str] = mapped_column(String(150), default="")

    mitigation: Mapped[str] = mapped_column(Text, default="")

    # Optional traceability to a recommendation already on record for
    # this risk -- not enforced with a hard FK constraint so a
    # recommendation can still be deleted independently.
    linked_recommendation_id: Mapped[int | None] = mapped_column(
        ForeignKey("safety_recommendations.id", ondelete="SET NULL"),
        nullable=True,
    )

    review_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, onupdate=func.now()
    )

    linked_recommendation: Mapped["SafetyRecommendationRecord | None"] = relationship()


class IncidentRecord(Base):
    __tablename__ = "incident_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    title: Mapped[str] = mapped_column(String(200))

    # Accident / Incident / Near Miss / Hazard / Safety Report / Operational Event
    event_type: Mapped[str] = mapped_column(String(30), default="Safety Report", index=True)

    category: Mapped[str] = mapped_column(String(100), default="", index=True)

    severity: Mapped[str] = mapped_column(String(20), default="Medium", index=True)

    # New -> Triaged -> Investigating -> Analysed -> Action Required -> Resolved -> Closed
    status: Mapped[str] = mapped_column(String(30), default="New", index=True)

    description: Mapped[str] = mapped_column(Text, default="")

    occurred_at: Mapped[date | None] = mapped_column(Date, nullable=True)

    location: Mapped[str] = mapped_column(String(200), default="")

    airport: Mapped[str] = mapped_column(String(200), default="")

    aircraft: Mapped[str] = mapped_column(String(150), default="")

    operator: Mapped[str] = mapped_column(String(150), default="")

    flight_phase: Mapped[str] = mapped_column(String(100), default="")

    weather: Mapped[str] = mapped_column(String(100), default="")

    assigned_investigator: Mapped[str] = mapped_column(String(150), default="")

    # Blank = submitted anonymously through the Safety Reporting portal.
    reported_by: Mapped[str] = mapped_column(String(150), default="")

    linked_recommendation_id: Mapped[int | None] = mapped_column(
        ForeignKey("safety_recommendations.id", ondelete="SET NULL"),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, onupdate=func.now()
    )

    linked_recommendation: Mapped["SafetyRecommendationRecord | None"] = relationship()


class InvestigationRecord(Base):
    __tablename__ = "investigation_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # An investigation is always worked against a specific incident --
    # required, not nullable, per the product's stated model.
    incident_id: Mapped[int] = mapped_column(
        ForeignKey("incident_records.id", ondelete="CASCADE"), index=True
    )

    lead_investigator: Mapped[str] = mapped_column(String(150), default="")

    # Open -> In Progress -> Pending Review -> Complete
    status: Mapped[str] = mapped_column(String(30), default="Open", index=True)

    summary: Mapped[str] = mapped_column(Text, default="")

    root_cause: Mapped[str] = mapped_column(Text, default="")

    contributing_factors: Mapped[list] = mapped_column(JSONB, default=list)

    started_at: Mapped[date | None] = mapped_column(Date, nullable=True)

    target_completion: Mapped[date | None] = mapped_column(Date, nullable=True)

    completed_at: Mapped[date | None] = mapped_column(Date, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, onupdate=func.now()
    )

    incident: Mapped["IncidentRecord"] = relationship()

    timeline: Mapped[list["InvestigationTimelineEntry"]] = relationship(
        back_populates="investigation", cascade="all, delete-orphan",
        order_by="InvestigationTimelineEntry.occurred_at",
    )

    evidence: Mapped[list["InvestigationEvidenceItem"]] = relationship(
        back_populates="investigation", cascade="all, delete-orphan",
        order_by="InvestigationEvidenceItem.created_at",
    )


class InvestigationEvidenceItem(Base):
    """
    A structured evidence entry (not a file/attachment -- no file
    storage backend exists) an investigator logs against an
    investigation: what it is, what kind of evidence it is, and an
    optional reference/citation.
    """

    __tablename__ = "investigation_evidence_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    investigation_id: Mapped[int] = mapped_column(
        ForeignKey("investigation_records.id", ondelete="CASCADE"), index=True
    )

    title: Mapped[str] = mapped_column(String(200))

    description: Mapped[str] = mapped_column(Text, default="")

    source_type: Mapped[str] = mapped_column(String(50), default="Other")

    reference: Mapped[str] = mapped_column(String(500), default="")

    added_by: Mapped[str] = mapped_column(String(150), default="")

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    investigation: Mapped["InvestigationRecord"] = relationship(back_populates="evidence")


class InvestigationTimelineEntry(Base):
    __tablename__ = "investigation_timeline_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    investigation_id: Mapped[int] = mapped_column(
        ForeignKey("investigation_records.id", ondelete="CASCADE"), index=True
    )

    occurred_at: Mapped[date | None] = mapped_column(Date, nullable=True)

    note: Mapped[str] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    investigation: Mapped["InvestigationRecord"] = relationship(back_populates="timeline")


class SafetyActionRecord(Base):
    __tablename__ = "safety_action_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    title: Mapped[str] = mapped_column(String(200))

    description: Mapped[str] = mapped_column(Text, default="")

    # Optional: an action can extend a specific recommendation's
    # workflow into a verifiable task, or stand alone.
    linked_recommendation_id: Mapped[int | None] = mapped_column(
        ForeignKey("safety_recommendations.id", ondelete="SET NULL"),
        nullable=True,
    )

    owner: Mapped[str] = mapped_column(String(150), default="")

    priority: Mapped[str] = mapped_column(String(20), default="Medium", index=True)

    # Open -> In Progress -> Verification -> Closed
    status: Mapped[str] = mapped_column(String(20), default="Open", index=True)

    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    verification_notes: Mapped[str] = mapped_column(Text, default="")

    closed_at: Mapped[date | None] = mapped_column(Date, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, onupdate=func.now()
    )

    linked_recommendation: Mapped["SafetyRecommendationRecord | None"] = relationship()

    comments: Mapped[list["SafetyActionComment"]] = relationship(
        back_populates="action", cascade="all, delete-orphan",
        order_by="SafetyActionComment.created_at",
    )


class SafetyActionComment(Base):
    __tablename__ = "safety_action_comments"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    action_id: Mapped[int] = mapped_column(
        ForeignKey("safety_action_records.id", ondelete="CASCADE"), index=True
    )

    author: Mapped[str] = mapped_column(String(150), default="")

    text: Mapped[str] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    action: Mapped["SafetyActionRecord"] = relationship(back_populates="comments")


class AlertAcknowledgement(Base):
    """
    Alerts themselves are computed live from real data on every request
    (see src/api/services/alert_service.py) rather than stored -- this
    table only records that a specific, deterministically-keyed alert
    has been acknowledged, so it stops reappearing in the feed.
    """

    __tablename__ = "alert_acknowledgements"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    alert_key: Mapped[str] = mapped_column(String(255), unique=True, index=True)

    acknowledged_by: Mapped[str] = mapped_column(String(150), default="")

    acknowledged_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class PredictionLog(Base):
    __tablename__ = "prediction_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    experiment_id: Mapped[int] = mapped_column(
        ForeignKey("experiments.id"), index=True
    )

    input_features: Mapped[dict] = mapped_column(JSONB)

    predicted_class: Mapped[str] = mapped_column(String(100))

    probabilities: Mapped[dict] = mapped_column(JSONB)

    shap_explanation: Mapped[list] = mapped_column(JSONB)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    experiment: Mapped["Experiment"] = relationship(back_populates="predictions")
